Add namespace logic to coreir backend module dict
Fixes an error such as:
```
../magma/magma/compile.py:64: in compile
    result = compiler.compile()
../magma/magma/backend/coreir/coreir_compiler.py:71: in compile
    backend.compile(self.main, opts)
../magma/magma/backend/coreir/coreir_backend.py:75: in compile
    transformer.run()
../magma/magma/backend/coreir/coreir_transformer.py:97: in run
    child.run()
../magma/magma/backend/coreir/coreir_transformer.py:98: in run
    self.run_self()
../magma/magma/backend/coreir/coreir_transformer.py:240: in run_self
    self.coreir_module.definition = self.get_coreir_defn()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <magma.backend.coreir.coreir_transformer.DefinitionTransformer object at 0x7f727dba8880>

    def get_coreir_defn(self):
>       coreir_defn = self.coreir_module.new_definition()
E       AttributeError: 'Generator' object has no attribute 'new_definition'

../magma/magma/backend/coreir/coreir_transformer.py:243: AttributeError
```

that is encountered when using a circuit named `add` since it is
clobbered by a module of the same name (the coreir.add primitive).  Does
this by storing module references separated by namespaces (using
separate dictionaries).  Updates the compile API to return the namespace
-> module map dictionary rather than just a single module map.